"""Config precedence, coercion and validation tests."""

from __future__ import annotations

import pytest

from uzum_scraper.config import Config
from uzum_scraper.errors import ConfigError


def test_token_bearer_prefix_stripped():
    cfg = Config.load(overrides={"auth_token": "Bearer ABC123", "iid": "x"}, env_file=None)
    assert cfg.auth_token == "ABC123"
    assert cfg.has_token


def test_invalid_language_raises():
    with pytest.raises(ConfigError):
        Config.load(overrides={"language": "fr-FR", "iid": "x"}, env_file=None)


def test_env_layer_and_override_precedence(monkeypatch, tmp_path):
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path))
    monkeypatch.setenv("UZUM_MIN_DELAY", "1.5")
    monkeypatch.setenv("UZUM_LANGUAGE", "ru-RU")
    cfg = Config.load(env_file=None)
    assert cfg.min_delay == 1.5
    assert cfg.language == "ru-RU"
    # explicit override beats env
    cfg2 = Config.load(overrides={"min_delay": 0.1}, env_file=None)
    assert cfg2.min_delay == 0.1


def test_iid_autogenerated_and_cached(monkeypatch, tmp_path):
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path))
    monkeypatch.delenv("UZUM_IID", raising=False)
    cfg = Config.load(env_file=None)
    assert cfg.iid  # generated
    cfg2 = Config.load(env_file=None)
    assert cfg2.iid == cfg.iid  # cached & stable


def test_require_token_message():
    cfg = Config.load(overrides={"auth_token": "", "iid": "x"}, env_file=None)
    with pytest.raises(ConfigError):
        cfg.require_token()


def test_redacted_masks_token():
    cfg = Config.load(overrides={"auth_token": "SECRETTOKEN", "iid": "x"}, env_file=None)
    assert cfg.redacted()["auth_token"] == "***OKEN"


def test_numeric_coercion_from_strings():
    cfg = Config.load(overrides={"timeout": "12", "max_retries": "3", "iid": "x"}, env_file=None)
    assert cfg.timeout == 12.0 and isinstance(cfg.timeout, float)
    assert cfg.max_retries == 3 and isinstance(cfg.max_retries, int)
